server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

FRONTEND_URL: ${FRONTEND_URL:https://utubehub-frontend.onrender.com}

spring:
  datasource:
    url: jdbc:postgresql://${AIVEN_PG_HOST:pg-2ff57b18-alagesan-0eb8.b.aivencloud.com}:${AIVEN_PG_PORT:15331}/${AIVEN_PG_DATABASE:utubehub}?sslmode=require
    username: ${AIVEN_PG_USER:avnadmin}
    password: ${AIVEN_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/youtube.readonly
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
