spring:
  application:
    name: utubehub-backend
  profiles:
    active: local

server:
  port: 8080
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
